/*
 * Copyright 2025 Thorsten Ludewig (t.ludewig@gmail.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.l9g.crypto.vault.sample.controller;


import jakarta.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Enumeration;
import java.util.LinkedHashMap;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.info.BuildProperties;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * REST controller for providing application build information.
 * <p>
 * This controller exposes an endpoint to retrieve build-time information,
 * such as the application version, build timestamp, and other properties
 * generated by the Spring Boot Maven plugin.
 *
 * @author Thorsten Ludewig (t.ludewig@gmail.com)
 */

@RestController
@RequestMapping(path = "/api/v1/buildinfo",
                produces = MediaType.APPLICATION_JSON_VALUE)
@RequiredArgsConstructor
@Slf4j
public class BuildInfo
{
  /**
   * Auto-configured by Spring Boot, provides access to build-time information of the application.
   */
  private final BuildProperties buildProperties;

  @GetMapping
  /**
   * Retrieves the application's build properties.
   * <p>
   * The properties are collected from the {@link BuildProperties} bean, sorted
   * alphabetically by key, and returned as a map.
   *
   * @return A {@link Map} containing the build properties as key-value pairs.
   */
  public Map<String, Object> buildinfoGET(HttpServletRequest request)
  {
    log.debug("buildinfoGET");

    LinkedHashMap<String, Object> out = new LinkedHashMap<>();

    // 1) deine Build-Infos wie bisher
    ArrayList<String> keys = new ArrayList<>();
    buildProperties.forEach(p -> keys.add(p.getKey()));
    Collections.sort(keys);
    LinkedHashMap<String, String> properties = new LinkedHashMap<>();
    for(String key : keys)
    {
      properties.put(key, buildProperties.get(key));
    }
    out.put("build", properties);

    // 2) Request/Scheme Debug
    LinkedHashMap<String, Object> req = new LinkedHashMap<>();
    req.put("scheme", request.getScheme());
    req.put("serverName", request.getServerName());
    req.put("serverPort", request.getServerPort());
    req.put("requestURL", String.valueOf(request.getRequestURL()));
    req.put("requestURI", request.getRequestURI());
    req.put("remoteAddr", request.getRemoteAddr());

    /*
    req.put("xForwardedProto", request.getHeader("X-Forwarded-Proto"));
    req.put("xForwardedHost", request.getHeader("X-Forwarded-Host"));
    req.put("xForwardedPort", request.getHeader("X-Forwarded-Port"));
    req.put("forwarded", request.getHeader("Forwarded"));
     */
    out.put("request", req);

    // optional: alle Header (für 1-2 Tests ok, danach wieder rausnehmen)
    LinkedHashMap<String, String> headers = new LinkedHashMap<>();
    Enumeration<String> names = request.getHeaderNames();
    if(names != null)
    {
      while(names.hasMoreElements())
      {
        String name = names.nextElement();
        headers.put(name, request.getHeader(name));
      }
    }
    out.put("headers", headers);

    return out;

  }

}
